name: Build and Test Spring Boot App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Set up Maven
        uses: actions/setup-maven@v2
        with:
          maven-version: '3.6.3'

      - name: Set environment variables from GitHub Secrets
        run: |
          echo "spring.datasource.username=${{ secrets.DB_USERNAME }}" >> $GITHUB_ENV
          echo "spring.datasource.password=${{ secrets.DB_PASSWORD }}" >> $GITHUB_ENV
          echo "google.api.key=${{ secrets.GOOGLE_API_KEY }}" >> $GITHUB_ENV
          echo "security.jwt.secret-key=${{ secrets.JWT_SECRET_KEY }}" >> $GITHUB_ENV

      - name: Build with Maven
        run: mvn clean install -DskipTests=false

      - name: Run tests
        run: mvn test
